# Generated by Django 3.2.5 on 2021-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='tag1',
            field=models.ManyToManyField(related_name='tags1', to='nextCoder.Tags'),
        ),
        migrations.AddField(
            model_name='talks',
            name='tag2',
            field=models.ManyToManyField(related_name='tags2', to='nextCoder.Tags'),
        ),
    ]
