# Generated by Django 3.2.5 on 2021-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0002_auto_20210729_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
