# Generated by Django 3.2.6 on 2021-08-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0004_remove_talks_tag2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talks',
            old_name='tag1',
            new_name='tags',
        ),
    ]
