# Generated by Django 3.2.6 on 2021-08-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0005_rename_tag1_talks_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='max_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
