# Generated by Django 3.2.6 on 2021-08-24 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0006_talks_max_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='talks',
            name='start_hour',
            field=models.TimeField(default=datetime.datetime(2021, 8, 24, 12, 24, 2, 315232, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talks',
            name='talk_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 24, 12, 24, 10, 247637, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
