# Generated by Django 3.2.6 on 2021-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0008_alter_talks_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
