# Generated by Django 3.2.6 on 2021-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0010_alter_talks_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
