# Generated by Django 3.2.6 on 2021-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0011_alter_talks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='attendants',
        ),
        migrations.AddField(
            model_name='talks',
            name='difficulty',
            field=models.CharField(choices=[('', 'Difficulty'), ('Introductory', 'Introductory'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talks',
            name='language',
            field=models.CharField(choices=[('', 'Language'), ('Spanish', 'Spanish'), ('English', 'English'), ('French', 'French'), ('Russian', 'Russiian'), ('Italian', 'Italian'), ('German', 'German'), ('Indi', 'Indi'), ('Chinese', 'Chinese'), ('Japanase', 'Japanese'), ('Arabian', 'Arabian'), ('Other', 'Other')], default='Spanish', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talks',
            name='duration',
            field=models.CharField(blank=True, choices=[('', 'Duration'), ('-30', '<30min'), ('30-1', '30min-1h'), ('1-1.5', '1h-1.5h'), ('2-2.5', '2h-2.5h'), ('2.5-3', '2.5h-3h'), ('+3', '>3h')], max_length=64, null=True),
        ),
    ]
