# Generated by Django 3.2.6 on 2021-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0012_auto_20210825_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags1', to='nextCoder.Tags'),
        ),
    ]
