# Generated by Django 3.2.6 on 2021-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0019_alter_talks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='about_author',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talks',
            name='prerrequesites',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talks',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='talks',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
