# Generated by Django 3.2.6 on 2021-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0020_auto_20210925_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
