# Generated by Django 3.2.6 on 2021-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0022_alter_talks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
