# Generated by Django 3.2.6 on 2022-01-14 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0023_alter_talks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='attendants',
            field=models.ManyToManyField(related_name='attendants', to=settings.AUTH_USER_MODEL),
        ),
    ]
