# Generated by Django 3.2.6 on 2022-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCoder', '0024_talks_attendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='how_to_attend_meeting',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
